### ISSUE TITLE
Fatal error: Uncaught TypeError: vsprintf(): Argument #2 ($values) must be of type array, string given in ~/.composer/vendor/squizlabs/php_codesniffer/src/Files/File.php:1056

### ISSUE THREAD

**Issue by goodevilgenius** [WordPress/WordPress-Coding-Standards#2021]
## Bug Description

1. Ran `phpcs --standard=WordPress /path/to/file.php`
2. Saw exception

## Minimal Code Snippet

The issue happens when running this command:
```bash
phpcs --standard=WordPress /path/to/file.php
```

... over a file containing this code:
```php
function foo
{

}
```

## Error Code

Expected exactly one space between closing parenthesis and opening control structure; "T_WHITESPACE" found.

## Custom ruleset

None

## Environment

| Question               | Answer
| ------------------------| -------
| PHP version             | 8.0.13
| PHP_CodeSniffer version | 3.6.1
| WPCS version            | `stable` branch
| WPCS install type       | `git clone`

## Additional Context (optional)

Stacktrace:

```
Fatal error: Uncaught TypeError: vsprintf(): Argument #2 ($values) must be of type array, string given in ~/.composer/vendor/squizlabs/php_codesniffer/src/Files/File.php:1056
Stack trace:
#0 ~/.composer/vendor/squizlabs/php_codesniffer/src/Files/File.php(1056): vsprintf('Expected exactl...', '\n')
#1 ~/.composer/vendor/squizlabs/php_codesniffer/src/Files/File.php(672): PHP_CodeSniffer\Files\File->addMessage(true, 'Expected exactl...', 15, 1, 'ExtraSpaceAfter...', '\n', 5, true)
#2 ~/.composer/vendor/squizlabs/php_codesniffer/src/Files/File.php(780): PHP_CodeSniffer\Files\File->addError('Expected exactl...', 57, 'ExtraSpaceAfter...', '\n', 0, true)
#3 ~/.local/share/wpcs/WordPress/Sniffs/WhiteSpace/ControlStructureSpacingSniff.php(396): PHP_CodeSniffer\Files\File->addFixableError('Expected exactl...', 57, 'ExtraSpaceAfter...', '\n')
#4 ~/.local/share/wpcs/WordPress/Sniff.php(910): WordPressCS\WordPress\Sniffs\WhiteSpace\ControlStructureSpacingSniff->process_token(57)
#5 ~/.composer/vendor/squizlabs/php_codesniffer/src/Files/File.php(498): WordPressCS\WordPress\Sniff->process(Object(PHP_CodeSniffer\Files\LocalFile), 57)
#6 ~/.composer/vendor/squizlabs/php_codesniffer/src/Files/LocalFile.php(92): PHP_CodeSniffer\Files\File->process()
#7 ~/.composer/vendor/squizlabs/php_codesniffer/src/Runner.php(631): PHP_CodeSniffer\Files\LocalFile->process()
#8 ~/.composer/vendor/squizlabs/php_codesniffer/src/Runner.php(434): PHP_CodeSniffer\Runner->processFile(Object(PHP_CodeSniffer\Files\LocalFile))
#9 ~/.composer/vendor/squizlabs/php_codesniffer/src/Runner.php(114): PHP_CodeSniffer\Runner->run()
#10 ~/.composer/vendor/squizlabs/php_codesniffer/bin/phpcs(18): PHP_CodeSniffer\Runner->runPHPCS()
#11 {main}
  thrown in ~/.composer/vendor/squizlabs/php_codesniffer/src/Files/File.php on line 1056
```

This diff fixes the issue:

```diff
diff --git a/WordPress/Sniffs/WhiteSpace/ControlStructureSpacingSniff.php b/WordPress/Sniffs/WhiteSpace/ControlStructureSpacingSniff.php
index 5f7b9a3c..293d78c7 100644
--- a/WordPress/Sniffs/WhiteSpace/ControlStructureSpacingSniff.php
+++ b/WordPress/Sniffs/WhiteSpace/ControlStructureSpacingSniff.php
@@ -392,7 +392,7 @@ class ControlStructureSpacingSniff extends Sniff {
 					$error,
 					$stackPtr,
 					'ExtraSpaceAfterCloseParenthesis',
-					$this->tokens[ ( $parenthesisCloser + 1 ) ]['content']
+					$this->tokens[ ( $parenthesisCloser + 1 ) ]
 				);
 
 				if ( true === $fix ) {
```

## Tested Against `develop` branch?
- [ ] I have verified the issue still exists in the `develop` branch of WPCS.
    * I did not. I tried, but got a completely different error: "Referenced sniff PHPCSUtils does not exist

**Comment by goodevilgenius** [comment]
@jrfnl Thanks. I couldn't find the previous issue.

I'll just cherry-pick that commit into my local branch, since I couldn't get develop to work.

**Comment by Mte90** [comment]
I am facing the same error but the latest release is 2.3.0 of may 2020...

**Comment by bgoewert** [comment]
Still seeing this same issue using the latest release (v2.3.0 May 2020).
@jrfnl Any update on that next release?

**Comment by ZachWatkins** [comment]
I am also experiencing this issue locally.
PHP: 8.1.7
squizlabs/php_codesniffer 3.7.1
wp-coding-standards/wpcs: 2.3.0
